var React = require("react");
var ReactDOM = require("react-dom");
var $ = require('jquery');
var marked = require('marked');

var CommentBox = React.createClass({
    getInitialState: function() {
        return {data: []}
    },
    // Ajax call to retrieve JSON from the server
    loadCommentsFromServer: function () {
        $.ajax({
            url: this.props.url,
            dataType: 'json',
            cache: false,
            // Comment Box UI will automatically updated when state changes
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString())
            }.bind(this)
        });
    },
    // Executed when the comment box is rendered
    componentDidMount: function() {
        this.loadCommentsFromServer();
        // Sets a sort of CRON job to poll the server after the first comment load
        setInterval(this.loadCommentsFromServer, this.props.pollInterval);
    },
    render: function() {
        return (
            <div className="commentBox">
                <h1>Comments</h1>
                <CommentList data={this.state.data}/>
                <CommentForm/>
            </div>
        );
    }
});

var CommentList = React.createClass({
    render: function() {
        var commentNodes = this.props.data.map(function(comment) {
            return (
                <Comment author={comment.author}>
                    {comment.text}
                </Comment>
            );
        });
        return (
            <div className="commentList">
                {commentNodes}
            </div>
        );
    }
});

var CommentForm = React.createClass({
    render: function() {
        return (
            <form className="commentForm">
                <input type="text" placeholder="Your name" />
                <input type="text" placeholder="Say something..." />
                <input type="submit" value="Post" />
            </form>
        );
    }
});

var Comment = React.createClass({
    render: function() {
        return (
            <div className="comment">
                <h2 className="commentAuthor">
                    {this.props.author}
                </h2>
                <span dangerouslySetInnerHTML={this.rawMarkup()} />
            </div>
       );
    },
    /* Do this so that HTML generated by markdown will not be escaped by React's XSS protection */
    rawMarkup: function() {
        var rawMarkup = marked(this.props.children.toString(), {sanitize: true});
        return { __html: rawMarkup };
    }
});

ReactDOM.render(
    <CommentBox url="/reactjs-sandbox/src/comments-tut/comments.json" pollInterval={2000}/>,
    document.getElementById('content')
);