var React = require("react");
var marked = require('marked');

var Comment = React.createClass({
    render: function() {
        return (
            <div className="comment">
                <h3 className="commentAuthor">
                    {this.props.author}
                </h3>
                <span dangerouslySetInnerHTML={this.rawMarkup()} />
            </div>
        );
    },
    /* Do this so that HTML generated by markdown will not be escaped by React's XSS protection */
    rawMarkup: function() {
        var rawMarkup = marked(this.props.children.toString(), {sanitize: true});
        return { __html: rawMarkup };
    }
});

module.exports = Comment;